added 1 and 2 task block
js-tasks-ru/js-20220311_sersurgut88 pull request #1
Opened 2022-03-18 09:18 UTC by SerSurgut

2022-03-18 09:18 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dosandk должен запустить тесты.

2022-03-18 16:28 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2022-03-18 16:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === "asc" ? sortArr : sortArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-03-18 16:29 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return fields.reduce((cur, value) => {
good 👍

2022-03-18 16:29 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let key in obj) {
good 👍

2022-03-18 16:29 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-03-22 15:34 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const keys = path.split(".");
👍 лайк за использование замыкания!

2022-03-22 15:34 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    keys.reduce((acc, value) => (acc ? acc[value] : acc), product);
у `reduce` есть небольшой тонкий момент, мы не можем использовать `break`

2022-03-22 15:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let _str = string[0];
не именуйте переменные с `_`

2022-03-22 15:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
good 👍

2022-03-22 15:35 UTC, dosandk approved these changes
good 👍

2022-03-22 15:36 UTC, merged